CC = c++

CFLAGS = -Wall -Wextra -Werror -std=c++98

CFILE = Contact.cpp PhoneBook.cpp main.cpp

NAME = Awesome_PhoneBook

all:
	$(CC) $(CFLAGS) $(CFILE) -o $(NAME)

clean:
	rm -f $(NAME)

re: clean all