CC = c++

CFLAGS = -Wall -Wextra -Werror -std=c++98

CFILE = main.cpp  newZombie.cpp  randomChump.cpp  Zombie.cpp

NAME = ZMBBY

all:
	$(CC) $(CFLAGS) $(CFILE) -o $(NAME)

clean:
	rm -f $(NAME)

re: clean all